baseURL = 'https://cerberus.cl/'
languageCode = 'en-us'
title = 'cerberus analitica corp'
[params]
  subtitle = 'Less than 15 seconds to comply'
  [params.contact]
    email = 'contact@cerberus.cl'
theme = 'ananke'

